Repository DIT112-V21/group-10, pull requests merged in 2021-04, with the labels that each got.

#9 Update smartcar.ino
  arduino/smartcar/smartcar.ino
Labels: Sprint 1, enhancement, good first issue, user story

#12 Sprint1
  arduino/Manual.md
  arduino/smartcar/smartcar.ino
Labels: Sprint 1, documentation, help wanted, user story

#24 Sprint 2 commits, connection established between app and example arduino sketch
  androidGeoBot/.gradle/6.5/fileChanges/last-build.bin
  androidGeoBot/.gradle/6.5/fileHashes/fileHashes.lock
  androidGeoBot/.gradle/6.5/gc.properties
  androidGeoBot/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  androidGeoBot/.gradle/buildOutputCleanup/cache.properties
  androidGeoBot/.gradle/checksums/checksums.lock
  androidGeoBot/.gradle/checksums/md5-checksums.bin
  androidGeoBot/.gradle/checksums/sha1-checksums.bin
  androidGeoBot/.gradle/vcs-1/gc.properties
  androidGeoBot/.idea/androidGeoBot.iml
  androidGeoBot/.idea/gradle.xml
  androidGeoBot/.idea/jarRepositories.xml
  androidGeoBot/.idea/modules.xml
  androidGeoBot/.idea/workspace.xml
  androidGeoBot/app/.idea/app.iml
  androidGeoBot/app/build.gradle
  androidGeoBot/app/local.properties
  androidGeoBot/app/src/main/AndroidManifest.xml
  androidGeoBot/app/src/main/java/com/example/androidgeobot/Client.java
  androidGeoBot/app/src/main/java/com/example/androidgeobot/ManualActivity.java
  androidGeoBot/app/src/main/java/com/example/androidgeobot/MqttClient.java
  androidGeoBot/app/src/main/res/layout/activity_manual.xml
  androidGeoBot/build.gradle
  arduino/sketch_successConnection/sketch_successConnection.ino
Labels: Sprint 2

#29 Removed duplicate code from ManualActivity.java
  .gitignore
  androidGeoBot/app/src/main/java/com/example/androidgeobot/ManualActivity.java
Labels: bug

#27 Manual screen added
  androidGeoBot/app/src/main/res/drawable-v24/accelerate_down.png
  androidGeoBot/app/src/main/res/drawable-v24/accelerate_up.png
  androidGeoBot/app/src/main/res/drawable-v24/break_button.png
  androidGeoBot/app/src/main/res/drawable-v24/down_button.png
  androidGeoBot/app/src/main/res/drawable-v24/group.png
  androidGeoBot/app/src/main/res/drawable-v24/ic_launcher_background.xml
  androidGeoBot/app/src/main/res/drawable-v24/left_button.png
  androidGeoBot/app/src/main/res/drawable-v24/right_button.png
  androidGeoBot/app/src/main/res/drawable-v24/steering_wheel.png
  androidGeoBot/app/src/main/res/drawable-v24/vector.png
  androidGeoBot/app/src/main/res/layout/activity_manual.xml
Labels: Sprint 2, user story

#56 Update Readme
  README.md
Labels: documentation
