Repository DIT112-V21/group-10, pull requests merged in 2021-05, with the labels that each got.

#58 Joystick imoprove
  androidGeoBot/.gradle/6.5/fileHashes/fileHashes.lock
  androidGeoBot/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  androidGeoBot/.idea/workspace.xml
  androidGeoBot/app/.idea/gradle.xml
  androidGeoBot/app/.idea/markdown-navigator.xml
  androidGeoBot/app/src/main/java/com/example/androidgeobot/Client.java
  androidGeoBot/app/src/main/java/com/example/androidgeobot/ManualActivity.java
  androidGeoBot/app/src/main/res/layout/activity_manual.xml
  arduino/othercars/othercars.ino
  arduino/smartcar/smartcar.ino
Labels: Sprint 3, enhancement

#73 Retrained cascade classifier for car object with updated dataset.
  androidGeoBot/app/src/main/assets/cascade.xml
Labels: Sprint 3, user story

#83 The other cars have random speed and angle. Other methods also got re…
  arduino/othercars/othercars.ino
Labels: Sprint 3, Sprint 4, enhancement

#85 Update othercars.ino with highly needed tree avoidance
  arduino/othercars/othercars.ino
Labels: enhancement

#94 Joystick improvements2
  androidGeoBot/app/src/main/java/com/example/androidtank/ManualActivity.java
  androidGeoBot/app/src/main/java/com/example/androidtank/opencv/Detection.java
  androidGeoBot/app/src/main/java/com/example/androidtank/opencv/ImageProcessor.java
  androidGeoBot/app/src/main/java/com/example/androidtank/utilities/Client.java
  androidGeoBot/app/src/main/java/com/example/androidtank/utilities/HandleFiles.java
  arduino/smartcar/smartcar.ino
Labels: Sprint 4, enhancement, user story

#95 adding timer feature
  androidGeoBot/app/src/main/java/com/example/androidtank/ManualActivity.java
  androidGeoBot/app/src/main/res/layout/activity_manual.xml
  arduino/smartcar/smartcar.ino
Labels: Sprint 4

#109 Change broker in app
  androidGeoBot/.gitignore
  androidGeoBot/app/src/main/java/com/example/androidtank/MainActivity.java
  androidGeoBot/app/src/main/java/com/example/androidtank/MainVideoView.java
  androidGeoBot/app/src/main/java/com/example/androidtank/ManualActivity.java
  androidGeoBot/app/src/main/java/com/example/androidtank/opencv/Detection.java
  androidGeoBot/app/src/main/java/com/example/androidtank/utilities/Client.java
  androidGeoBot/app/src/main/java/com/example/androidtank/utilities/HandleFiles.java
  androidGeoBot/app/src/main/res/drawable-v24/bg_brake_button.xml
  androidGeoBot/app/src/main/res/drawable-v24/bg_top_gradient.xml
  androidGeoBot/app/src/main/res/layout/activity_main.xml
  androidGeoBot/app/src/main/res/values/strings.xml
  androidGeoBot/app/src/main/res/values/styles.xml
  androidGeoBot/openCVLibrary3414/build/intermediates/incremental/packageDebugResources/compile-file-map.properties
  androidGeoBot/openCVLibrary3414/build/outputs/logs/manifest-merger-debug-report.txt
  arduino/smartcar/smartcar.ino
Labels: Sprint 4, enhancement

#112 Readme fixes
  README.md
  arduino/README.md
Labels: documentation
